version: "3"

services:

  # PostgreSQL database for authentication, storing compendium content,
  # etc.
  database:
    image: postgres:12.2-alpine
    container_name: tec-database
    env_file:
      - .env
    volumes:
      - site-db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - tec-net

  # Apache Solr instance for text search
  search:
    build:
      context: docker/solr/
      args:
        POSTGRES_JDBC_VERSION: "42.2.11"
    image: tec-solr:latest
    container_name: tec-search
    depends_on:
      - database
    env_file:
      - .env
    #volumes:
    #  - solrdata:/var/solr:rw
    ports:
      - "8983:8983"
    networks:
      - tec-net
    command:
      - solr-precreate
      - compendium

  # Webserver
  gunicorn:
    build:
      context: .
      dockerfile: docker/gunicorn/Dockerfile
    image: tec-gunicorn:latest
    container_name: tec-gunicorn
    depends_on:
      - database
      - search
    environment:
      DATABASE_ENGINE: "postgres"
    env_file:
      - .env
    volumes:
      - ./src:/var/src/:ro
      # - staticfiles:/var/src/assets:rw
    ports:
      - "5000:5000"
    networks:
      - tec-net
      - tec-nginx

  # Proxyserver
  proxy:
    build:
      context: docker/nginx/
    image: tec-proxy:latest
    container_name: tec-proxy
    ports:
      - 8000:80
    # volumes:
    #   # Shared volume with the gunicorn server that allows us to
    #   # serve static files.
    #   - staticfiles:/opt/services/tec-gunicorn/assets:ro
    depends_on:
      - gunicorn
    networks:
      - tec-nginx

  # Webserver cache
  cache:
    image: memcached:1.6-alpine
    container_name: tec-cache

networks:
  tec-net:
  tec-nginx:

volumes:
  site-db:
  solrdata:
  # staticfiles:
