version: "3"

services:

  # PostgreSQL database for authentication, storing compendium content,
  # etc.
  tec-database:
    image: postgres:12.2-alpine
    container_name: tec-database
    env_file:
      - .env
    volumes:
      - site-db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - tec-net

  # Apache Solr instance for text search
  tec-search:
    build:
      context: deploy_tools/solr/
      args:
        POSTGRES_JDBC_VERSION: "42.2.11"
    image: tec-solr
    container_name: tec-search
    depends_on:
      - tec-database
    env_file:
      - .env
    #volumes:
    #  - solrdata:/var/solr:rw
    ports:
      - "8983:8983"
    networks:
      - tec-net
    command:
      - solr-precreate
      - compendium

  # Webserver
  tec-gunicorn:
    build:
      context: .
      dockerfile: deploy_tools/gunicorn/Dockerfile
    image: tec-gunicorn
    container_name: tec-gunicorn
    depends_on:
      - tec-database
      - tec-search
    environment:
      DATABASE_ENGINE: "postgres"
    env_file:
      - .env
    volumes:
      - ./src:/var/src/:ro
      - assets-volume:/opt/services/tec-gunicorn/assets
    ports:
      - "5000:5000"
    networks:
      - tec-net
      - tec-nginx

  # Proxyserver
  tec-proxy:
    image: nginx:1.17.9
    container_name: tec-proxy
    ports:
      - 8000:80
    volumes:
      - ./deploy_tools/nginx:/etc/nginx/conf.d
      - assets-volume:/opt/services/tec-gunicorn/assets
    depends_on:
      - tec-gunicorn
    networks:
      - tec-nginx


networks:
  tec-net:
  tec-nginx:

volumes:
  site-db:
  solrdata:
  assets-volume:
