version: "3"

services:

  # Webserver
  gunicorn:
    build:
      context: .
      dockerfile: docker/gunicorn/Dockerfile
    image: tec-gunicorn:latest
    container_name: tec-gunicorn
    user: www-data
    env_file:
      - .env
    volumes:
      - staticfiles:/var/www/static:rw
      - ./src:/var/www/src:ro
    ports:
      - "5000:5000"
    networks:
      - tec-net

  # Proxyserver
  proxy:
    build:
      context: docker/nginx/
    image: tec-proxy:latest
    container_name: tec-proxy
    environment:
      SERVER_NAME: encryptioncompendium.org
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Shared volume with the gunicorn server that allows us to
      # serve static files.
      - staticfiles:/opt/services/tec-gunicorn/static:ro
      - letsencrypt:/tls:rw
    depends_on:
      - gunicorn
    networks:
      - tec-net

  # Webserver cache
  cache:
    image: memcached:1.6-alpine
    container_name: tec-cache
    networks:
      - tec-net

networks:
  tec-net:

volumes:
  staticfiles:
  letsencrypt:
