version: "3"

services:

  # PostgreSQL database for authentication, storing compendium content,
  # etc.
  database:
    image: postgres:12.2-alpine
    container_name: tec-database
    env_file:
      - .env
    volumes:
      - site-db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - tec-net

  # Apache Solr instance for text search
  search:
    build:
      context: docker/solr/
      args:
        POSTGRES_JDBC_VERSION: "42.2.11"
    image: tec-solr:latest
    container_name: tec-search
    depends_on:
      - database
    env_file:
      - .env
    #volumes:
    #  - solrdata:/var/solr:rw
    ports:
      - "8983:8983"
    networks:
      - tec-net
    command:
      - solr-precreate
      - compendium

  # Webserver
  gunicorn:
    build:
      context: .
      dockerfile: docker/gunicorn/Dockerfile
    image: tec-gunicorn:latest
    container_name: tec-gunicorn
    user: www-data
    depends_on:
      - database
      - search
    environment:
      DATABASE_ENGINE: "postgres"
    env_file:
      - .env
    volumes:
      - staticfiles:/var/www/static:rw
      - ./src:/var/www/src:ro
    ports:
      - "5000:5000"
    networks:
      - tec-net

  # Proxyserver
  proxy:
    build:
      context: docker/nginx/
    image: tec-proxy:latest
    container_name: tec-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Shared volume with the gunicorn server that allows us to
      # serve static files.
      - staticfiles:/opt/services/tec-gunicorn/static:ro
      - letsencrypt:/etc/letsencrypt:rw
    depends_on:
      - gunicorn
    networks:
      - tec-net

  # Webserver cache
  cache:
    image: memcached:1.6-alpine
    container_name: tec-cache
    networks:
      - tec-net

networks:
  tec-net:

volumes:
  site-db:
  solrdata:
  staticfiles:
  letsencrypt:
