# Generated by Django 3.0.3 on 2020-03-30 03:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorname", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CompendiumEntryTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tagname", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publishername",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompendiumEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=250, null=True)),
                ("abstract", models.CharField(blank=True, max_length=5000, null=True)),
                ("url", models.URLField(blank=True, max_length=300, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "publisher_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "authors_cs",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1900)],
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(12),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(31),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("authors", models.ManyToManyField(blank=True, to="entries.Author")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="entries.Publisher",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, to="entries.CompendiumEntryTag"),
                ),
            ],
            options={"db_table": "compendium",},
        ),
    ]
