# Generated by Django 3.0.1 on 2020-03-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compendiumentry",
            name="author_text",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="compendiumentry",
            name="authors",
            field=models.ManyToManyField(
                blank=True, null=True, to="research_assistant.Author"
            ),
        ),
    ]
