# Generated by Django 3.0.1 on 2020-01-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compendiumentrytag",
            name="tagname",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
