# Generated by Django 3.0.1 on 2020-02-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_assistant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="compendiumentry",
            name="authors",
            field=models.ManyToManyField(blank=True, to="research_assistant.Author"),
        ),
    ]
