# Generated by Django 3.0.1 on 2020-02-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_assistant", "0002_auto_20200228_0749"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorname", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(name="Author",),
        migrations.AlterField(
            model_name="compendiumentry",
            name="authors",
            field=models.ManyToManyField(blank=True, to="research_assistant.Authors"),
        ),
    ]
