# Generated by Django 3.0.1 on 2020-03-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_assistant", "0002_auto_20200308_0749"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compendiumentry",
            name="authors",
            field=models.ManyToManyField(blank=True, to="research_assistant.Author"),
        ),
    ]
