# Generated by Django 3.0.1 on 2020-02-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research_assistant", "0003_auto_20200228_0758"),
    ]

    operations = [
        migrations.RenameModel(old_name="Authors", new_name="Author",),
        migrations.RemoveField(model_name="compendiumentry", name="authors",),
    ]
