# Generated by Django 3.0.1 on 2020-03-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research_assistant", "0003_auto_20200308_0750"),
    ]

    operations = [
        migrations.RenameField(
            model_name="compendiumentry",
            old_name="author_text",
            new_name="authors_text",
        ),
    ]
